# 🌐 SCRIPT TO GENERATE HTML VIEWER V4 FOR CORRECTED FIGURES

# 1. 🧹 Clean environment
rm(list = ls())

# 2. 📦 Load necessary libraries
library(tidyverse)

# 3. ⚙️ Load configuration
source("config/config_pipeline_2.R")
source("config/parameters.R") # To get panel descriptions and scientific questions

# Paths
figure_path_v4 <- file.path(figures_dir, "figure_1_corrected.png")
panel_a_path <- file.path(figures_dir, "panel_a_overview.png")
panel_b_path <- file.path(figures_dir, "panel_b_gt_analysis.png")
panel_c_path <- file.path(figures_dir, "panel_c_spectrum.png")
panel_d_path <- file.path(figures_dir, "panel_d_placeholder.png")
html_output_path_v4 <- file.path(base_dir, "figure_1_viewer_v4.html")

# Data for HTML (example, can be loaded dynamically)
figure_title_v4 <- "FIGURE 1: Dataset Characterization & G>T Oxidative Stress Landscape"
report_version <- "v4.0"
report_date <- format(Sys.Date(), "%Y-%m-%d")

# Descriptions from parameters.R (updated to English - CLEARER)
panel_a_desc_v4 <- "This panel shows the dataset evolution from 'Raw Entries' (68,968 rows in original file, some containing multiple mutations) to 'Individual SNVs' (110,199 separate mutations after splitting and filtering PM entries). It also displays the overall distribution of mutation types. Addresses SQ1.1 and SQ1.3."
panel_b_desc_v4 <- "This panel visualizes the positional frequency of G>T mutations across miRNA positions (1-22) and compares G>T prevalence in seed region (positions 2-8) versus non-seed regions. It addresses SQ1.2 and SQ3.1."
panel_c_desc_v4 <- "This panel shows the proportion of different G>X mutation types (G>A, G>C, G>T) at each miRNA position and highlights the top 10 most frequent mutation types across the entire dataset. It addresses SQ1.3."
panel_d_desc_v4 <- "This panel is currently a placeholder as we focus on initial characterization steps. Advanced miRNA-specific analysis will be added in subsequent iterations."

# Metrics (from the test script results)
original_snvs_count <- 68968
processed_snvs_count <- 110199
unique_mirnas_count <- 1462
gt_mutations_count <- 8033

cat("🌐 Generating HTML Viewer v4...\n")

html_content_v4 <- paste0(
  "<!DOCTYPE html>\n",
  "<html lang=\"en\">\n",
  "<head>\n",
  "    <meta charset=\"UTF-8\">\n",
  "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n",
  "    <title>Pipeline_2: Figure 1 - Dataset Characterization (Corrected)</title>\n",
  "    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700&display=swap\" rel=\"stylesheet\">\n",
  "    <style>\n",
  "        :root {\n",
  "            --bg-color: #1a202c;\n",
  "            --card-bg: #2d3748;\n",
  "            --text-color: #e2e8f0;\n",
  "            --primary-color: #63b3ed;\n",
  "            --secondary-color: #4fd1c5;\n",
  "            --accent-color: #f6e05e;\n",
  "            --border-color: #4a5568;\n",
  "            --header-bg: #242d3a;\n",
  "            --tab-inactive: #4a5568;\n",
  "            --tab-active: #63b3ed;\n",
  "            --modal-bg: rgba(0, 0, 0, 0.9);\n",
  "        }\n",
  "        body {\n",
  "            font-family: 'Inter', sans-serif;\n",
  "            background-color: var(--bg-color);\n",
  "            color: var(--text-color);\n",
  "            margin: 0;\n",
  "            padding: 20px;\n",
  "            line-height: 1.6;\n",
  "        }\n",
  "        .container {\n",
  "            max-width: 1600px;\n",
  "            margin: 0 auto;\n",
  "            background: var(--card-bg);\n",
  "            border-radius: 15px;\n",
  "            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.5);\n",
  "            overflow: hidden;\n",
  "        }\n",
  "        .header {\n",
  "            background: var(--header-bg);\n",
  "            padding: 40px;\n",
  "            text-align: center;\n",
  "            border-bottom: 1px solid var(--border-color);\n",
  "        }\n",
  "        .header h1 {\n",
  "            font-size: 2.8em;\n",
  "            margin-bottom: 10px;\n",
  "            font-weight: 700;\n",
  "            color: var(--primary-color);\n",
  "        }\n",
  "        .header .subtitle {\n",
  "            font-size: 1.4em;\n",
  "            opacity: 0.9;\n",
  "            margin-bottom: 5px;\n",
  "            color: var(--text-color);\n",
  "        }\n",
  "        .header .version {\n",
  "            font-size: 0.9em;\n",
  "            opacity: 0.7;\n",
  "            margin-top: 10px;\n",
  "            color: var(--text-color);\n",
  "        }\n",
  "        .tabs {\n",
  "            display: flex;\n",
  "            justify-content: center;\n",
  "            background: var(--header-bg);\n",
  "            border-bottom: 1px solid var(--border-color);\n",
  "        }\n",
  "        .tab-button {\n",
  "            background: none;\n",
  "            border: none;\n",
  "            padding: 15px 30px;\n",
  "            color: var(--tab-inactive);\n",
  "            font-size: 1.1em;\n",
  "            cursor: pointer;\n",
  "            transition: all 0.3s ease;\n",
  "            font-weight: 600;\n",
  "        }\n",
  "        .tab-button:hover {\n",
  "            color: var(--primary-color);\n",
  "            background-color: rgba(99, 179, 237, 0.1);\n",
  "        }\n",
  "        .tab-button.active {\n",
  "            color: var(--tab-active);\n",
  "            border-bottom: 3px solid var(--tab-active);\n",
  "        }\n",
  "        .tab-content {\n",
  "            padding: 40px;\n",
  "        }\n",
  "        .section-title {\n",
  "            font-size: 2em;\n",
  "            color: var(--primary-color);\n",
  "            margin-bottom: 25px;\n",
  "            text-align: center;\n",
  "            font-weight: 700;\n",
  "        }\n",
  "        .info-grid {\n",
  "            display: grid;\n",
  "            grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));\n",
  "            gap: 25px;\n",
  "            margin: 30px 0;\n",
  "        }\n",
  "        .info-card {\n",
  "            background: var(--bg-color);\n",
  "            padding: 25px;\n",
  "            border-radius: 10px;\n",
  "            border-left: 5px solid var(--secondary-color);\n",
  "            transition: transform 0.2s, box-shadow 0.2s;\n",
  "            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.2);\n",
  "        }\n",
  "        .info-card:hover {\n",
  "            transform: translateY(-5px);\n",
  "            box-shadow: 0 12px 25px rgba(0, 0, 0, 0.3);\n",
  "        }\n",
  "        .info-card .label {\n",
  "            font-size: 0.9em;\n",
  "            color: var(--primary-color);\n",
  "            text-transform: uppercase;\n",
  "            letter-spacing: 1px;\n",
  "            margin-bottom: 10px;\n",
  "            font-weight: 600;\n",
  "        }\n",
  "        .info-card .value {\n",
  "            font-size: 2em;\n",
  "            color: var(--accent-color);\n",
  "            font-weight: 700;\n",
  "        }\n",
  "        .figure-container {\n",
  "            background: var(--bg-color);\n",
  "            border-radius: 12px;\n",
  "            padding: 30px;\n",
  "            margin: 30px auto;\n",
  "            border: 1px solid var(--border-color);\n",
  "            box-shadow: 0 8px 20px rgba(0, 0, 0, 0.3);\n",
  "            text-align: center;\n",
  "        }\n",
  "        .figure-container img {\n",
  "            max-width: 100%;\n",
  "            height: auto;\n",
  "            border-radius: 8px;\n",
  "            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.2);\n",
  "            cursor: zoom-in;\n",
  "            transition: transform 0.3s ease, box-shadow 0.3s ease;\n",
  "        }\n",
  "        .figure-container img:hover {\n",
  "            transform: scale(1.01);\n",
  "            box-shadow: 0 8px 20px rgba(0, 0, 0, 0.35);\n",
  "        }\n",
  "        .panel-grid {\n",
  "            display: grid;\n",
  "            grid-template-columns: repeat(auto-fit, minmax(45%, 1fr));\n",
  "            gap: 30px;\n",
  "            margin-top: 30px;\n",
  "        }\n",
  "        .panel-card {\n",
  "            background: var(--bg-color);\n",
  "            padding: 25px;\n",
  "            border-radius: 10px;\n",
  "            border: 1px solid var(--border-color);\n",
  "            box-shadow: 0 5px 15px rgba(0, 0, 0, 0.2);\n",
  "        }\n",
  "        .panel-card h3 {\n",
  "            color: var(--secondary-color);\n",
  "            font-size: 1.5em;\n",
  "            margin-bottom: 15px;\n",
  "            font-weight: 600;\n",
  "        }\n",
  "        .panel-card p {\n",
  "            color: var(--text-color);\n",
  "            font-size: 1em;\n",
  "            margin-bottom: 15px;\n",
  "        }\n",
  "        .panel-card img {\n",
  "            width: 100%;\n",
  "            height: auto;\n",
  "            border-radius: 8px;\n",
  "            margin-top: 15px;\n",
  "            box-shadow: 0 3px 10px rgba(0, 0, 0, 0.15);\n",
  "            cursor: zoom-in;\n",
  "        }\n",
  "        .findings-list ul {\n",
  "            list-style: none;\n",
  "            padding: 0;\n",
  "        }\n",
  "        .findings-list li {\n",
  "            background: var(--card-bg);\n",
  "            border-left: 4px solid var(--primary-color);\n",
  "            padding: 15px 20px;\n",
  "            margin-bottom: 15px;\n",
  "            border-radius: 8px;\n",
  "            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);\n",
  "            font-size: 1.1em;\n",
  "        }\n",
  "        .findings-list li strong {\n",
  "            color: var(--secondary-color);\n",
  "        }\n",
  "        .documentation-links ul {\n",
  "            list-style: none;\n",
  "            padding: 0;\n",
  "            display: grid;\n",
  "            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));\n",
  "            gap: 20px;\n",
  "        }\n",
  "        .documentation-links li {\n",
  "            background: var(--card-bg);\n",
  "            border-left: 4px solid var(--accent-color);\n",
  "            padding: 15px 20px;\n",
  "            border-radius: 8px;\n",
  "            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);\n",
  "        }\n",
  "        .documentation-links a {\n",
  "            color: var(--primary-color);\n",
  "            text-decoration: none;\n",
  "            font-weight: 600;\n",
  "        }\n",
  "        .documentation-links a:hover {\n",
  "            text-decoration: underline;\n",
  "        }\n",
  "        .footer {\n",
  "            background: var(--header-bg);\n",
  "            color: var(--text-color);\n",
  "            padding: 30px;\n",
  "            text-align: center;\n",
  "            margin-top: 40px;\n",
  "            border-top: 1px solid var(--border-color);\n",
  "        }\n",
  "        .footer a {\n",
  "            color: var(--primary-color);\n",
  "            text-decoration: none;\n",
  "        }\n",
  "        .footer a:hover {\n",
  "            text-decoration: underline;\n",
  "        }\n",
  "        /* Modal for image zoom */\n",
  "        .modal {\n",
  "            display: none;\n",
  "            position: fixed;\n",
  "            z-index: 1000;\n",
  "            padding-top: 50px;\n",
  "            left: 0;\n",
  "            top: 0;\n",
  "            width: 100%;\n",
  "            height: 100%;\n",
  "            overflow: auto;\n",
  "            background-color: var(--modal-bg);\n",
  "        }\n",
  "        .modal-content {\n",
  "            margin: auto;\n",
  "            display: block;\n",
  "            width: 90%;\n",
  "            max-width: 1800px;\n",
  "            border-radius: 10px;\n",
  "        }\n",
  "        .close {\n",
  "            position: absolute;\n",
  "            top: 30px;\n",
  "            right: 45px;\n",
  "            color: #f1f1f1;\n",
  "            font-size: 50px;\n",
  "            font-weight: bold;\n",
  "            transition: 0.3s;\n",
  "            cursor: pointer;\n",
  "        }\n",
  "        .close:hover,\n",
  "        .close:focus {\n",
  "            color: #bbb;\n",
  "            text-decoration: none;\n",
  "            cursor: pointer;\n",
  "        }\n",
  "    </style>\n",
  "</head>\n",
  "<body>\n",
  "    <div class=\"container\">\n",
  "        <!-- Header -->\n",
  "        <div class=\"header\">\n",
  "            <h1>&#128640; PIPELINE_2: Optimized miRNA Analysis</h1>\n",
  "            <div class=\"subtitle\">", figure_title_v4, "</div>\n",
  "            <div class=\"version\">Version ", report_version, " | Date: ", report_date, " | CORRECTED MUTATION FORMAT</div>\n",
  "        </div>\n",
  "\n",
  "        <!-- Tabs -->\n",
  "        <div class=\"tabs\">\n",
  "            <button class=\"tab-button active\" onclick=\"openTab(event, 'completeFigure')\">Complete Figure</button>\n",
  "            <button class=\"tab-button\" onclick=\"openTab(event, 'individualPanels')\">Individual Panels</button>\n",
  "            <button class=\"tab-button\" onclick=\"openTab(event, 'keyFindings')\">Key Findings</button>\n",
  "            <button class=\"tab-button\" onclick=\"openTab(event, 'documentation')\">Documentation</button>\n",
  "        </div>\n",
  "\n",
  "        <!-- Tab Content: Complete Figure -->\n",
  "        <div id=\"completeFigure\" class=\"tab-content\">\n",
  "            <h2 class=\"section-title\">&#128200; Dataset Summary (Corrected)</h2>\n",
  "            <div class=\"info-grid\">\n",
  "                <div class=\"info-card\">\n",
  "                    <div class=\"label\">Raw Entries (Original File)</div>\n",
  "                    <div class=\"value\">", scales::comma(original_snvs_count), "</div>\n",
  "                </div>\n",
  "                <div class=\"info-card\">\n",
  "                    <div class=\"label\">Individual SNVs (Processed)</div>\n",
  "                    <div class=\"value\">", scales::comma(processed_snvs_count), "</div>\n",
  "                </div>\n",
  "                <div class=\"info-card\">\n",
  "                    <div class=\"label\">Unique miRNAs</div>\n",
  "                    <div class=\"value\">", scales::comma(unique_mirnas_count), "</div>\n",
  "                </div>\n",
  "                <div class=\"info-card\">\n",
  "                    <div class=\"label\">G>T Mutations</div>\n",
  "                    <div class=\"value\">", scales::comma(gt_mutations_count), "</div>\n",
  "                </div>\n",
  "            </div>\n",
  "\n",
  "            <h2 class=\"section-title\">&#128202; ", figure_title_v4, "</h2>\n",
  "            <div class=\"figure-container\">\n",
  "                <img id=\"figure1_img_v4\" src=\"figures/figure_1_corrected.png\" alt=\"Figure 1: Dataset Characterization (Corrected)\">\n",
  "            </div>\n",
  "        </div>\n",
  "\n",
  "        <!-- Tab Content: Individual Panels -->\n",
  "        <div id=\"individualPanels\" class=\"tab-content\" style=\"display:none;\">\n",
  "            <h2 class=\"section-title\">&#128202; Individual Figure Panels (Corrected)</h2>\n",
  "            <div class=\"panel-grid\">\n",
  "                <div class=\"panel-card\">\n",
  "                    <h3>Panel A: Dataset Evolution & Overall Mutation Types</h3>\n",
  "                    <p>", panel_a_desc_v4, "</p>\n",
  "                    <img src=\"figures/panel_a_overview.png\" alt=\"Panel A Overview\">\n",
  "                </div>\n",
  "                <div class=\"panel-card\">\n",
  "                    <h3>Panel B: G>T Positional Analysis</h3>\n",
  "                    <p>", panel_b_desc_v4, "</p>\n",
  "                    <img src=\"figures/panel_b_gt_analysis.png\" alt=\"Panel B G>T Analysis\">\n",
  "                </div>\n",
  "                <div class=\"panel-card\">\n",
  "                    <h3>Panel C: Mutation Spectrum</h3>\n",
  "                    <p>", panel_c_desc_v4, "</p>\n",
  "                    <img src=\"figures/panel_c_spectrum.png\" alt=\"Panel C Spectrum\">\n",
  "                </div>\n",
  "                <div class=\"panel-card\">\n",
  "                    <h3>Panel D: Advanced Analysis (Pending)</h3>\n",
  "                    <p>", panel_d_desc_v4, "</p>\n",
  "                    <img src=\"figures/panel_d_placeholder.png\" alt=\"Panel D Placeholder\">\n",
  "                </div>\n",
  "            </div>\n",
  "        </div>\n",
  "\n",
  "        <!-- Tab Content: Key Findings -->\n",
  "        <div id=\"keyFindings\" class=\"tab-content\" style=\"display:none;\">\n",
  "            <h2 class=\"section-title\">&#128269; Key Scientific Findings (Corrected Format)</h2>\n",
  "            <div class=\"findings-list\">\n",
  "                <ul>\n",
  "                    <li><strong>SQ1.1 (Dataset Structure & Quality):</strong> The original file contains 68,968 raw entries (rows), with each entry potentially containing multiple mutations separated by commas. After splitting these entries and filtering out Perfect Matches (PM), we obtained 110,199 individual SNVs ready for analysis.</li>\n",
  "                    <li><strong>SQ1.2 (G>T Positional Distribution):</strong> Found 8,033 G>T mutations (7.3% of all mutations) with clear positional patterns across miRNA positions.</li>\n",
  "                    <li><strong>SQ1.3 (Prevalent G>X Mutation Types):</strong> T>C mutations are most frequent (19,569), followed by A>G (17,081) and G>A (13,403). G>T represents 8,033 mutations.</li>\n",
  "                    <li><strong>SQ1.4 (Top miRNAs for G>T):</strong> Analysis pending as we focus on initial characterization steps.</li>\n",
  "                    <li><strong>Data Quality:</strong> Successfully corrected mutation format from TC/AG to T>C/A>G format for proper scientific interpretation.</li>\n",
  "                    <li><strong>Coverage:</strong> Analysis covers 1,462 unique miRNAs with comprehensive positional analysis.</li>\n",
  "                </ul>\n",
  "            </div>\n",
  "        </div>\n",
  "\n",
  "        <!-- Tab Content: Documentation -->\n",
  "        <div id=\"documentation\" class=\"tab-content\" style=\"display:none;\">\n",
  "            <h2 class=\"section-title\">&#128193; Project Documentation & Status</h2>\n",
  "            <div class=\"documentation-links\">\n",
  "                <ul>\n",
  "                    <li><a href=\"README.md\" target=\"_blank\">README.md: Project Overview</a></li>\n",
  "                    <li><a href=\"CHANGELOG.md\" target=\"_blank\">CHANGELOG.md: Version History</a></li>\n",
  "                    <li><a href=\"FIGURE_LAYOUTS.md\" target=\"_blank\">FIGURE_LAYOUTS.md: Figure Designs</a></li>\n",
  "                    <li><a href=\"DESIGN_DECISIONS.md\" target=\"_blank\">DESIGN_DECISIONS.md: Design Rationale</a></li>\n",
  "                    <li><a href=\"MAINTENANCE_GUIDE.md\" target=\"_blank\">MAINTENANCE_GUIDE.md: Maintenance Guide</a></li>\n",
  "                    <li><a href=\"PROJECT_STATUS.md\" target=\"_blank\">PROJECT_STATUS.md: Current Project Status</a></li>\n",
  "                </ul>\n",
  "            </div>\n",
  "        </div>\n",
  "\n",
  "        <!-- Footer -->\n",
  "        <div class=\"footer\">\n",
  "            <p>Generated by Pipeline_2 v4 | <a href=\"README.md\" target=\"_blank\">Documentation</a> | <a href=\"CHANGELOG.md\" target=\"_blank\">Changelog</a></p>\n",
  "        </div>\n",
  "    </div>\n",
  "\n",
  "    <!-- Modal for image zoom -->\n",
  "    <div id=\"myModal\" class=\"modal\">\n",
  "        <span class=\"close\">&times;</span>\n",
  "        <img class=\"modal-content\" id=\"img01\">\n",
  "    </div>\n",
  "\n",
  "    <script>\n",
  "        function openTab(evt, tabName) {\n",
  "            var i, tabcontent, tablinks;\n",
  "            tabcontent = document.getElementsByClassName(\"tab-content\");\n",
  "            for (i = 0; i < tabcontent.length; i++) {\n",
  "                tabcontent[i].style.display = \"none\";\n",
  "            }\n",
  "            tablinks = document.getElementsByClassName(\"tab-button\");\n",
  "            for (i = 0; i < tablinks.length; i++) {\n",
  "                tablinks[i].className = tablinks[i].className.replace(\" active\", \"\");\n",
  "            }\n",
  "            document.getElementById(tabName).style.display = \"block\";\n",
  "            evt.currentTarget.className += \" active\";\n",
  "        }\n",
  "\n",
  "        // Open the default tab on page load\n",
  "        document.addEventListener(\"DOMContentLoaded\", function() {\n",
  "            document.getElementsByClassName(\"tab-button\")[0].click();\n",
  "        });\n",
  "\n",
  "        // Get the modal\n",
  "        var modal = document.getElementById(\"myModal\");\n",
  "        var modalImg = document.getElementById(\"img01\");\n",
  "        var span = document.getElementsByClassName(\"close\")[0];\n",
  "\n",
  "        document.querySelectorAll('.figure-container img, .panel-card img').forEach(item => {\n",
  "            item.onclick = function(){\n",
  "                modal.style.display = \"block\";\n",
  "                modalImg.src = this.src;\n",
  "            }\n",
  "        });\n",
  "\n",
  "        span.onclick = function() {\n",
  "            modal.style.display = \"none\";\n",
  "        }\n",
  "        modal.onclick = function(event) {\n",
  "            if (event.target == modal) {\n",
  "                modal.style.display = \"none\";\n",
  "            }\n",
  "        }\n",
  "    </script>\n",
  "</body>\n",
  "</html>"
)

writeLines(html_content_v4, html_output_path_v4)

cat("✅ HTML Viewer v4 generated successfully\n")
cat("📁 Location:", html_output_path_v4, "\n\n")
cat("🌐 Opening in browser...\n")
browseURL(html_output_path_v4)
cat("✅ Done!\n")
