# 🌐 GENERAR HTML VIEWER PARA FIGURA 1

cat("🌐 Generando HTML Viewer para Figura 1...\n\n")

## 📁 RUTAS
base_dir <- "/Users/cesaresparza/New_Desktop/UCSD/8OG/final_analysis/pipeline_definitivo/pipeline_2"
figures_dir <- file.path(base_dir, "figures")
output_html <- file.path(base_dir, "figura_1_viewer.html")

## 📊 VERIFICAR QUE EXISTE LA FIGURA
figura_path <- file.path(figures_dir, "figura_1_caracterizacion_dataset.png")
if (!file.exists(figura_path)) {
  stop("❌ Figura no encontrada. Ejecuta test_figure_1.R primero")
}

## 🎨 CREAR HTML USANDO SPRINTF
html_lines <- c(
  '<!DOCTYPE html>',
  '<html lang="es">',
  '<head>',
  '    <meta charset="UTF-8">',
  '    <meta name="viewport" content="width=device-width, initial-scale=1.0">',
  '    <title>Pipeline_2: Figura 1 - Caracterización del Dataset</title>',
  '    <style>',
  '        * { margin: 0; padding: 0; box-sizing: border-box; }',
  '        body {',
  '            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;',
  '            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);',
  '            padding: 20px;',
  '            line-height: 1.6;',
  '        }',
  '        .container {',
  '            max-width: 1400px;',
  '            margin: 0 auto;',
  '            background: white;',
  '            border-radius: 15px;',
  '            box-shadow: 0 20px 60px rgba(0,0,0,0.3);',
  '            overflow: hidden;',
  '        }',
  '        .header {',
  '            background: linear-gradient(135deg, #2d3748 0%, #1a202c 100%);',
  '            color: white;',
  '            padding: 40px;',
  '            text-align: center;',
  '        }',
  '        .header h1 { font-size: 2.5em; margin-bottom: 10px; font-weight: 700; }',
  '        .header .subtitle { font-size: 1.2em; opacity: 0.9; }',
  sprintf('        .header .version { font-size: 0.9em; opacity: 0.7; margin-top: 10px; }'),
  '        .content { padding: 40px; }',
  '        .section { margin-bottom: 40px; }',
  '        .section-title {',
  '            font-size: 1.8em;',
  '            color: #2d3748;',
  '            margin-bottom: 15px;',
  '            padding-bottom: 10px;',
  '            border-bottom: 3px solid #667eea;',
  '            font-weight: 600;',
  '        }',
  '        .info-grid {',
  '            display: grid;',
  '            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));',
  '            gap: 20px;',
  '            margin: 30px 0;',
  '        }',
  '        .info-card {',
  '            background: linear-gradient(135deg, #f6f8fb 0%, #e9ecef 100%);',
  '            padding: 25px;',
  '            border-radius: 10px;',
  '            border-left: 5px solid #667eea;',
  '            transition: transform 0.2s, box-shadow 0.2s;',
  '        }',
  '        .info-card:hover {',
  '            transform: translateY(-5px);',
  '            box-shadow: 0 10px 25px rgba(102, 126, 234, 0.2);',
  '        }',
  '        .info-card .label {',
  '            font-size: 0.9em;',
  '            color: #718096;',
  '            text-transform: uppercase;',
  '            letter-spacing: 1px;',
  '            margin-bottom: 8px;',
  '            font-weight: 600;',
  '        }',
  '        .info-card .value {',
  '            font-size: 1.8em;',
  '            color: #2d3748;',
  '            font-weight: 700;',
  '        }',
  '        .figure-container {',
  '            background: #f7fafc;',
  '            border-radius: 10px;',
  '            padding: 30px;',
  '            margin: 30px 0;',
  '            border: 2px solid #e2e8f0;',
  '        }',
  '        .figure-container img {',
  '            width: 100%;',
  '            height: auto;',
  '            border-radius: 8px;',
  '            box-shadow: 0 10px 30px rgba(0,0,0,0.1);',
  '            cursor: pointer;',
  '            transition: transform 0.3s;',
  '        }',
  '        .figure-container img:hover { transform: scale(1.02); }',
  '        .panel-description {',
  '            background: white;',
  '            border-radius: 8px;',
  '            padding: 20px;',
  '            margin-top: 20px;',
  '            border-left: 4px solid #48bb78;',
  '        }',
  '        .panel-description h4 {',
  '            color: #2d3748;',
  '            margin-bottom: 10px;',
  '            font-size: 1.2em;',
  '        }',
  '        .panel-description ul { margin-left: 20px; color: #4a5568; }',
  '        .panel-description li { margin: 8px 0; }',
  '        .questions {',
  '            background: linear-gradient(135deg, #fff5f5 0%, #ffe5e5 100%);',
  '            border-radius: 10px;',
  '            padding: 25px;',
  '            margin: 20px 0;',
  '            border-left: 5px solid #f56565;',
  '        }',
  '        .questions h4 { color: #c53030; margin-bottom: 15px; font-size: 1.3em; }',
  '        .questions ul { margin-left: 20px; }',
  '        .questions li { margin: 10px 0; color: #742a2a; font-weight: 500; }',
  '        .footer {',
  '            background: #2d3748;',
  '            color: white;',
  '            padding: 30px;',
  '            text-align: center;',
  '        }',
  '        .footer a { color: #90cdf4; text-decoration: none; }',
  '        .footer a:hover { text-decoration: underline; }',
  '        .badge {',
  '            display: inline-block;',
  '            padding: 5px 15px;',
  '            border-radius: 20px;',
  '            font-size: 0.9em;',
  '            font-weight: 600;',
  '            margin: 5px;',
  '        }',
  '        .badge-success { background: #c6f6d5; color: #22543d; }',
  '        .badge-info { background: #bee3f8; color: #2c5282; }',
  '        .badge-warning { background: #feebc8; color: #7c2d12; }',
  '        .modal {',
  '            display: none;',
  '            position: fixed;',
  '            z-index: 999;',
  '            left: 0;',
  '            top: 0;',
  '            width: 100%;',
  '            height: 100%;',
  '            background-color: rgba(0,0,0,0.9);',
  '        }',
  '        .modal-content { margin: 50px auto; display: block; width: 95%; max-width: 1600px; }',
  '        .close {',
  '            position: absolute;',
  '            top: 30px;',
  '            right: 50px;',
  '            color: #f1f1f1;',
  '            font-size: 50px;',
  '            font-weight: bold;',
  '            cursor: pointer;',
  '        }',
  '        .close:hover { color: #bbb; }',
  '    </style>',
  '</head>',
  '<body>',
  '    <div class="container">',
  '        <div class="header">',
  '            <h1>🚀 PIPELINE_2: Análisis Optimizado de miRNAs</h1>',
  '            <div class="subtitle">Figura 1: Caracterización del Dataset</div>',
  sprintf('            <div class="version">Versión 0.1.0 | Fecha: %s</div>', format(Sys.Date(), "%d/%m/%Y")),
  '            <div style="margin-top: 20px;">',
  '                <span class="badge badge-success">✅ Implementada</span>',
  '                <span class="badge badge-info">📊 Datos Reales</span>',
  '                <span class="badge badge-warning">🔬 En Revisión</span>',
  '            </div>',
  '        </div>',
  '        <div class="content">',
  '            <div class="section">',
  '                <h2 class="section-title">📋 Resumen Ejecutivo</h2>',
  '                <div class="info-grid">',
  '                    <div class="info-card">',
  '                        <div class="label">SNVs Originales</div>',
  '                        <div class="value">68,968</div>',
  '                    </div>',
  '                    <div class="info-card">',
  '                        <div class="label">SNVs Procesados</div>',
  '                        <div class="value">111,785</div>',
  '                    </div>',
  '                    <div class="info-card">',
  '                        <div class="label">miRNAs Únicos</div>',
  '                        <div class="value">1,728</div>',
  '                    </div>',
  '                    <div class="info-card">',
  '                        <div class="label">Posiciones Analizadas</div>',
  '                        <div class="value">1-22</div>',
  '                    </div>',
  '                </div>',
  '            </div>',
  '            <div class="section">',
  '                <h2 class="section-title">🔬 Preguntas Científicas Respondidas</h2>',
  '                <div class="questions">',
  '                    <h4>Esta figura responde:</h4>',
  '                    <ul>',
  '                        <li>✅ ¿Cuál es la estructura y calidad del dataset?</li>',
  '                        <li>✅ ¿Dónde ocurren las mutaciones G>T en los miRNAs?</li>',
  '                        <li>✅ ¿Qué tipos de mutación G→X son más prevalentes?</li>',
  '                        <li>✅ ¿Cuáles son los miRNAs más susceptibles al estrés oxidativo?</li>',
  '                    </ul>',
  '                </div>',
  '            </div>',
  '            <div class="section">',
  '                <h2 class="section-title">📊 Figura 1: Caracterización Completa</h2>',
  '                <div class="figure-container">',
  '                    <img src="figures/figura_1_caracterizacion_dataset.png" ',
  '                         alt="Figura 1: Caracterización del Dataset"',
  '                         onclick="openModal(this)" id="mainFigure">',
  '                </div>',
  '                <div class="panel-description">',
  '                    <h4>📌 Panel A: Evolución del Dataset</h4>',
  '                    <ul>',
  '                        <li><strong>Qué muestra:</strong> Transformación de datos crudos (68,968) a procesados (111,785)</li>',
  '                        <li><strong>Insight:</strong> Split-collapse aumenta filas al separar mutaciones múltiples</li>',
  '                    </ul>',
  '                </div>',
  '                <div class="panel-description">',
  '                    <h4>📌 Panel B: Heatmap Posicional G>T</h4>',
  '                    <ul>',
  '                        <li><strong>Qué muestra:</strong> Distribución de G>T por posición (1-22)</li>',
  '                        <li><strong>Insight:</strong> Hotspots de estrés oxidativo</li>',
  '                        <li><strong>Inspiración:</strong> ⭐ Adaptado del paper</li>',
  '                    </ul>',
  '                </div>',
  '                <div class="panel-description">',
  '                    <h4>📌 Panel C: Tipos de Mutación G→X</h4>',
  '                    <ul>',
  '                        <li><strong>Qué muestra:</strong> Fracción de G>A, G>C, G>T por posición</li>',
  '                        <li><strong>Insight:</strong> Dominancia de G>T como marcador oxidativo</li>',
  '                        <li><strong>Inspiración:</strong> ⭐ Adaptado del paper</li>',
  '                    </ul>',
  '                </div>',
  '                <div class="panel-description">',
  '                    <h4>📌 Panel D: Top 15 miRNAs con G>T</h4>',
  '                    <ul>',
  '                        <li><strong>Qué muestra:</strong> miRNAs más afectados por estrés oxidativo</li>',
  '                        <li><strong>Insight:</strong> Candidatos para análisis funcional</li>',
  '                    </ul>',
  '                </div>',
  '            </div>',
  '            <div class="section">',
  '                <h2 class="section-title">🎨 Decisiones de Diseño</h2>',
  '                <div class="panel-description">',
  '                    <h4>Adaptaciones del Paper:</h4>',
  '                    <ul>',
  '                        <li><strong>Panel B:</strong> Heatmap horizontal posicional</li>',
  '                        <li><strong>Panel C:</strong> Barras apiladas para fracciones</li>',
  '                        <li><strong>Paleta:</strong> Viridis/Plasma (colorblind-friendly)</li>',
  '                        <li><strong>Layout:</strong> 2x2 grid (información + claridad)</li>',
  '                    </ul>',
  '                </div>',
  '            </div>',
  '            <div class="section">',
  '                <h2 class="section-title">🚀 Próximos Pasos</h2>',
  '                <div class="info-grid">',
  '                    <div class="info-card">',
  '                        <div class="label">Figura 2</div>',
  '                        <div class="value">⏳ Pendiente</div>',
  '                        <p style="margin-top: 10px; color: #4a5568; font-size: 0.9em;">',
  '                            Análisis G>T exclusivo ALS vs Control',
  '                        </p>',
  '                    </div>',
  '                    <div class="info-card">',
  '                        <div class="label">Figura 3</div>',
  '                        <div class="value">⏳ Pendiente</div>',
  '                        <p style="margin-top: 10px; color: #4a5568; font-size: 0.9em;">',
  '                            Análisis funcional (seed/pathways)',
  '                        </p>',
  '                    </div>',
  '                    <div class="info-card">',
  '                        <div class="label">Estadísticas</div>',
  '                        <div class="value">⏳ Pendiente</div>',
  '                        <p style="margin-top: 10px; color: #4a5568; font-size: 0.9em;">',
  '                            Tests formales, corrección FDR',
  '                        </p>',
  '                    </div>',
  '                </div>',
  '            </div>',
  '        </div>',
  '        <div class="footer">',
  '            <p><strong>Pipeline_2</strong> | Versión 0.1.0</p>',
  '            <p>Documentación: <a href="README.md">README</a> | ',
  '               <a href="FIGURE_LAYOUTS.md">Layouts</a> | ',
  '               <a href="DESIGN_DECISIONS.md">Decisiones</a></p>',
  sprintf('            <p style="margin-top: 15px; opacity: 0.7;">Generado: %s</p>', format(Sys.time(), "%Y-%m-%d %H:%M:%S")),
  '        </div>',
  '    </div>',
  '    <div id="imageModal" class="modal" onclick="closeModal()">',
  '        <span class="close">&times;</span>',
  '        <img class="modal-content" id="modalImage">',
  '    </div>',
  '    <script>',
  '        function openModal(img) {',
  '            var modal = document.getElementById("imageModal");',
  '            var modalImg = document.getElementById("modalImage");',
  '            modal.style.display = "block";',
  '            modalImg.src = img.src;',
  '        }',
  '        function closeModal() {',
  '            document.getElementById("imageModal").style.display = "none";',
  '        }',
  '        document.addEventListener("keydown", function(event) {',
  '            if (event.key === "Escape") closeModal();',
  '        });',
  '    </script>',
  '</body>',
  '</html>'
)

# Escribir HTML
writeLines(html_lines, output_html)

cat("✅ HTML Viewer generado exitosamente\n")
cat("📁 Ubicación:", output_html, "\n")
cat("\n🌐 Para ver los resultados, abre:\n")
cat("   ", output_html, "\n")