# 🌐 GENERATE HTML VIEWER V2 - MINIMAL TEXT, MAXIMUM VISUAL

cat("🌐 Generating HTML Viewer v2...\n\n")

## 📁 PATHS
base_dir <- "/Users/cesaresparza/New_Desktop/UCSD/8OG/final_analysis/pipeline_definitivo/pipeline_2"
figures_dir <- file.path(base_dir, "figures")
output_html <- file.path(base_dir, "figure_1_viewer_v2.html")

## 📊 CHECK FILES EXIST
required_files <- c(
  "figure_1_dataset_characterization_v2.png",
  "panel_a_overview.png",
  "panel_b_landscape.png",
  "panel_c_spectrum.png",
  "panel_d_profile.png"
)

for (file in required_files) {
  if (!file.exists(file.path(figures_dir, file))) {
    stop("❌ Missing file: ", file, ". Run test_figure_1_v2.R first")
  }
}

## 🎨 CREATE HTML
html_lines <- c(
  '<!DOCTYPE html>',
  '<html lang="en">',
  '<head>',
  '    <meta charset="UTF-8">',
  '    <meta name="viewport" content="width=device-width, initial-scale=1.0">',
  '    <title>Pipeline_2: Figure 1 - Dataset Characterization</title>',
  '    <style>',
  '        * { margin: 0; padding: 0; box-sizing: border-box; }',
  '        body {',
  '            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;',
  '            background: #0f172a;',
  '            color: #e2e8f0;',
  '            padding: 20px;',
  '        }',
  '        .container {',
  '            max-width: 1600px;',
  '            margin: 0 auto;',
  '            background: #1e293b;',
  '            border-radius: 12px;',
  '            box-shadow: 0 25px 50px rgba(0,0,0,0.5);',
  '            overflow: hidden;',
  '        }',
  '        .header {',
  '            background: linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%);',
  '            padding: 30px;',
  '            text-align: center;',
  '        }',
  '        .header h1 { font-size: 2.2em; margin-bottom: 8px; color: white; }',
  sprintf('        .header .meta { font-size: 0.95em; opacity: 0.9; color: #e0e7ff; }'),
  '        .tabs {',
  '            display: flex;',
  '            background: #334155;',
  '            border-bottom: 2px solid #475569;',
  '        }',
  '        .tab {',
  '            flex: 1;',
  '            padding: 15px;',
  '            text-align: center;',
  '            cursor: pointer;',
  '            transition: all 0.3s;',
  '            border-right: 1px solid #475569;',
  '            font-weight: 600;',
  '        }',
  '        .tab:last-child { border-right: none; }',
  '        .tab:hover { background: #475569; }',
  '        .tab.active { background: #6366f1; color: white; }',
  '        .content { padding: 30px; }',
  '        .tab-content { display: none; }',
  '        .tab-content.active { display: block; }',
  '        .figure-main {',
  '            background: white;',
  '            border-radius: 10px;',
  '            padding: 20px;',
  '            margin: 20px 0;',
  '        }',
  '        .figure-main img {',
  '            width: 100%;',
  '            height: auto;',
  '            border-radius: 8px;',
  '            cursor: pointer;',
  '            transition: transform 0.3s;',
  '        }',
  '        .figure-main img:hover { transform: scale(1.01); }',
  '        .panels-grid {',
  '            display: grid;',
  '            grid-template-columns: repeat(2, 1fr);',
  '            gap: 20px;',
  '            margin: 20px 0;',
  '        }',
  '        .panel-card {',
  '            background: #334155;',
  '            border-radius: 8px;',
  '            overflow: hidden;',
  '            transition: transform 0.2s;',
  '        }',
  '        .panel-card:hover { transform: translateY(-5px); }',
  '        .panel-card img {',
  '            width: 100%;',
  '            height: auto;',
  '            cursor: pointer;',
  '        }',
  '        .panel-info {',
  '            padding: 15px;',
  '            background: #475569;',
  '        }',
  '        .panel-info h4 { color: #e0e7ff; margin-bottom: 8px; font-size: 1.1em; }',
  '        .panel-info p { color: #cbd5e1; font-size: 0.9em; line-height: 1.5; }',
  '        .stats-grid {',
  '            display: grid;',
  '            grid-template-columns: repeat(4, 1fr);',
  '            gap: 15px;',
  '            margin: 20px 0;',
  '        }',
  '        .stat-card {',
  '            background: linear-gradient(135deg, #334155 0%, #475569 100%);',
  '            padding: 20px;',
  '            border-radius: 8px;',
  '            text-align: center;',
  '            border: 2px solid #64748b;',
  '        }',
  '        .stat-card .value {',
  '            font-size: 2em;',
  '            font-weight: 700;',
  '            color: #a5f3fc;',
  '            margin: 8px 0;',
  '        }',
  '        .stat-card .label {',
  '            font-size: 0.85em;',
  '            color: #94a3b8;',
  '            text-transform: uppercase;',
  '            letter-spacing: 1px;',
  '        }',
  '        .key-findings {',
  '            background: linear-gradient(135deg, #1e3a8a 0%, #1e40af 100%);',
  '            border-radius: 10px;',
  '            padding: 25px;',
  '            margin: 20px 0;',
  '            border-left: 5px solid #60a5fa;',
  '        }',
  '        .key-findings h3 { color: #bfdbfe; margin-bottom: 15px; }',
  '        .key-findings ul { margin-left: 20px; }',
  '        .key-findings li { margin: 10px 0; color: #dbeafe; }',
  '        .modal {',
  '            display: none;',
  '            position: fixed;',
  '            z-index: 999;',
  '            left: 0;',
  '            top: 0;',
  '            width: 100%;',
  '            height: 100%;',
  '            background: rgba(0,0,0,0.95);',
  '        }',
  '        .modal-content {',
  '            margin: 30px auto;',
  '            display: block;',
  '            width: 98%;',
  '            max-width: 1800px;',
  '        }',
  '        .close {',
  '            position: absolute;',
  '            top: 20px;',
  '            right: 40px;',
  '            color: white;',
  '            font-size: 40px;',
  '            font-weight: bold;',
  '            cursor: pointer;',
  '        }',
  '        .close:hover { color: #bbb; }',
  '    </style>',
  '</head>',
  '<body>',
  '    <div class="container">',
  '        <div class="header">',
  '            <h1>📊 miRNA Oxidative Stress Analysis</h1>',
  sprintf('            <div class="meta">Pipeline v2 | Figure 1 | %s</div>', format(Sys.Date(), "%Y-%m-%d")),
  '        </div>',
  '        ',
  '        <div class="tabs">',
  '            <div class="tab active" onclick="showTab(0)">Complete Figure</div>',
  '            <div class="tab" onclick="showTab(1)">Individual Panels</div>',
  '            <div class="tab" onclick="showTab(2)">Key Findings</div>',
  '            <div class="tab" onclick="showTab(3)">Documentation</div>',
  '        </div>',
  '        ',
  '        <div class="content">',
  '            <!-- TAB 0: Complete Figure -->',
  '            <div class="tab-content active">',
  '                <div class="stats-grid">',
  '                    <div class="stat-card">',
  '                        <div class="label">SNVs Processed</div>',
  '                        <div class="value">111,785</div>',
  '                    </div>',
  '                    <div class="stat-card">',
  '                        <div class="label">Unique miRNAs</div>',
  '                        <div class="value">1,728</div>',
  '                    </div>',
  '                    <div class="stat-card">',
  '                        <div class="label">Positions</div>',
  '                        <div class="value">1-22</div>',
  '                    </div>',
  '                    <div class="stat-card">',
  '                        <div class="label">Panels</div>',
  '                        <div class="value">4</div>',
  '                    </div>',
  '                </div>',
  '                <div class="figure-main">',
  '                    <img src="figures/figure_1_dataset_characterization_v2.png" ',
  '                         alt="Figure 1: Dataset Characterization"',
  '                         onclick="openModal(this)">',
  '                </div>',
  '            </div>',
  '            ',
  '            <!-- TAB 1: Individual Panels -->',
  '            <div class="tab-content">',
  '                <div class="panels-grid">',
  '                    <div class="panel-card">',
  '                        <img src="figures/panel_a_overview.png" onclick="openModal(this)">',
  '                        <div class="panel-info">',
  '                            <h4>Panel A: Overview</h4>',
  '                            <p>Dataset evolution + Mutation type distribution</p>',
  '                        </div>',
  '                    </div>',
  '                    <div class="panel-card">',
  '                        <img src="figures/panel_b_landscape.png" onclick="openModal(this)">',
  '                        <div class="panel-info">',
  '                            <h4>Panel B: Landscape</h4>',
  '                            <p>G>T positional distribution + Regional summary</p>',
  '                        </div>',
  '                    </div>',
  '                    <div class="panel-card">',
  '                        <img src="figures/panel_c_spectrum.png" onclick="openModal(this)">',
  '                        <div class="panel-info">',
  '                            <h4>Panel C: Spectrum</h4>',
  '                            <p>G>T fraction by position + Top mutation types</p>',
  '                        </div>',
  '                    </div>',
  '                    <div class="panel-card">',
  '                        <img src="figures/panel_d_profile.png" onclick="openModal(this)">',
  '                        <div class="panel-info">',
  '                            <h4>Panel D: Profile</h4>',
  '                            <p>Top miRNAs + Positional heatmap</p>',
  '                        </div>',
  '                    </div>',
  '                </div>',
  '            </div>',
  '            ',
  '            <!-- TAB 2: Key Findings -->',
  '            <div class="tab-content">',
  '                <div class="key-findings">',
  '                    <h3>🔬 Scientific Questions Answered</h3>',
  '                    <ul>',
  '                        <li>✅ What is the structure and quality of the dataset?</li>',
  '                        <li>✅ Where do G>T mutations occur in miRNAs?</li>',
  '                        <li>✅ What G→X mutation types are most prevalent?</li>',
  '                        <li>✅ Which miRNAs are most susceptible to oxidative stress?</li>',
  '                    </ul>',
  '                </div>',
  '                ',
  '                <div class="key-findings">',
  '                    <h3>💡 Key Insights</h3>',
  '                    <ul>',
  '                        <li><strong>Panel A:</strong> 68,968 raw → 111,785 processed SNVs (62% increase from separate_rows)</li>',
  '                        <li><strong>Panel B:</strong> G>T distribution reveals oxidative stress hotspots, seed region (2-8) highlighted</li>',
  '                        <li><strong>Panel C:</strong> G>T dominance confirmed as oxidative marker across all positions</li>',
  '                        <li><strong>Panel D:</strong> Top 12 miRNAs identified with positional profiles for functional analysis</li>',
  '                    </ul>',
  '                </div>',
  '                ',
  '                <div class="key-findings">',
  '                    <h3>🎨 Design Improvements (v2)</h3>',
  '                    <ul>',
  '                        <li>✅ All text in English (scientific standard)</li>',
  '                        <li>✅ Minimal text, maximum visual information</li>',
  '                        <li>✅ Integrated sub-panels (2 charts per panel)</li>',
  '                        <li>✅ Higher data density without clutter</li>',
  '                        <li>✅ Seed region highlighted consistently</li>',
  '                    </ul>',
  '                </div>',
  '            </div>',
  '            ',
  '            <!-- TAB 3: Documentation -->',
  '            <div class="tab-content">',
  '                <div class="key-findings">',
  '                    <h3>📚 Documentation Files</h3>',
  '                    <ul>',
  '                        <li><strong>README.md</strong> - Project overview and objectives</li>',
  '                        <li><strong>CHANGELOG.md</strong> - Version history (now v0.1.2)</li>',
  '                        <li><strong>FIGURE_LAYOUTS.md</strong> - Complete figure designs</li>',
  '                        <li><strong>DESIGN_DECISIONS.md</strong> - Documented rationale</li>',
  '                        <li><strong>MAINTENANCE_GUIDE.md</strong> - Update workflow</li>',
  '                        <li><strong>PROJECT_STATUS.md</strong> - Current progress</li>',
  '                    </ul>',
  '                </div>',
  '                ',
  '                <div class="stats-grid">',
  '                    <div class="stat-card">',
  '                        <div class="label">Version</div>',
  '                        <div class="value">0.1.2</div>',
  '                    </div>',
  '                    <div class="stat-card">',
  '                        <div class="label">Figures</div>',
  '                        <div class="value">1/3</div>',
  '                    </div>',
  '                    <div class="stat-card">',
  '                        <div class="label">Questions</div>',
  '                        <div class="value">4/12</div>',
  '                    </div>',
  '                    <div class="stat-card">',
  '                        <div class="label">Status</div>',
  '                        <div class="value" style="font-size: 1.5em;">✅</div>',
  '                    </div>',
  '                </div>',
  '            </div>',
  '        </div>',
  '    </div>',
  '    ',
  '    <!-- Modal -->',
  '    <div id="modal" class="modal" onclick="closeModal()">',
  '        <span class="close">&times;</span>',
  '        <img class="modal-content" id="modalImg">',
  '    </div>',
  '    ',
  '    <script>',
  '        function showTab(index) {',
  '            const tabs = document.querySelectorAll(".tab");',
  '            const contents = document.querySelectorAll(".tab-content");',
  '            tabs.forEach((tab, i) => {',
  '                tab.classList.toggle("active", i === index);',
  '                contents[i].classList.toggle("active", i === index);',
  '            });',
  '        }',
  '        ',
  '        function openModal(img) {',
  '            document.getElementById("modal").style.display = "block";',
  '            document.getElementById("modalImg").src = img.src;',
  '        }',
  '        ',
  '        function closeModal() {',
  '            document.getElementById("modal").style.display = "none";',
  '        }',
  '        ',
  '        document.addEventListener("keydown", (e) => {',
  '            if (e.key === "Escape") closeModal();',
  '        });',
  '    </script>',
  '</body>',
  '</html>'
)

# Write HTML
writeLines(html_lines, output_html)

cat("✅ HTML Viewer v2 generated successfully\n")
cat("📁 Location:", output_html, "\n")
cat("\n🌐 Opening in browser...\n")

# Open in browser
system(paste0("open '", output_html, "'"))

cat("✅ Done!\n")

