# =============================================================================
# PRESENTACIÓN HTML FINAL COMPLETA: ANÁLISIS DE SNVs EN miRNAs
# =============================================================================

# Cargar librerías necesarias
library(rmarkdown)
library(dplyr)
library(stringr)
library(ggplot2)
library(gridExtra)
library(viridis)
library(RColorBrewer)
library(knitr)
library(corrplot)

# Configurar directorio de trabajo
setwd("/Users/cesaresparza/New_Desktop/UCSD/8OG/final_analysis/tercer_intento")

# Crear directorio para la presentación HTML final
output_dir <- "presentacion_html_final"
if (!dir.exists(output_dir)) {
  dir.create(output_dir, recursive = TRUE)
}

cat("=== PRESENTACIÓN HTML FINAL COMPLETA ===\n")
cat("Generando presentación HTML con imágenes reales y conexión con paper original...\n\n")

# --- Crear el archivo R Markdown dinámicamente ---
rmd_content <- c(
  "---",
  "title: 'Análisis de SNVs en miRNAs: ALS vs Control'",
  "subtitle: 'Un estudio exhaustivo de la carga oxidativa y patrones mutacionales'",
  "author: 'Análisis basado en GSE168714: Circulating miR-181 is a prognostic biomarker for amyotrophic lateral sclerosis'",
  "date: '`r format(Sys.Date(), \"%d %B, %Y\")`'",
  "output:",
  "  ioslides_presentation:",
  "    css: custom.css",
  "    widescreen: true",
  "    transition: 0.4",
  "    theme: flatly",
  "    mathjax: https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML",
  "---",
  "",
  "```{r setup, include=FALSE}",
  "knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.align = 'center', fig.width = 10, fig.height = 6)",
  "base_path <- '/Users/cesaresparza/New_Desktop/UCSD/8OG/final_analysis/tercer_intento'",
  "```",
  "",
  "## Introducción y Contexto del Estudio",
  "",
  "### Paper Original de Referencia",
  "**Título**: \"Circulating miR-181 is a prognostic biomarker for amyotrophic lateral sclerosis\"",
  "**GEO**: GSE168714",
  "**Hallazgo Principal**: miR-181 como biomarcador pronóstico para ALS",
  "",
  "### Nuestro Enfoque Innovador",
  "- **Análisis de SNVs**: Variantes de nucleótido único en miRNAs",
  "- **Carga Oxidativa**: Enfoque en mutaciones G>T como indicador de daño oxidativo",
  "- **Análisis Posicional**: Distribución de SNVs en regiones funcionales (semilla vs no-semilla)",
  "- **Validación Técnica**: Identificación y exclusión de artefactos técnicos",
  "",
  "### Objetivos Principales",
  "- **Identificar** diferencias en patrones de SNVs oxidativos (G>T) en miRNAs entre pacientes con ALS y controles.",
  "- **Analizar** la distribución de SNVs por posición en los miRNAs, con énfasis en la región semilla.",
  "- **Desarrollar** métricas de carga oxidativa y correlacionarlas con datos clínicos.",
  "- **Validar** la robustez de los hallazgos y explorar posibles biomarcadores.",
  "",
  "---",
  "",
  "## Metodología: Preprocesamiento de Datos",
  "",
  "### Datos Iniciales",
  "- **Archivo**: `/Users/cesaresparza/New_Desktop/UCSD/8OG/results/Magen_ALS-bloodplasma/miRNA_count.Q33.txt`",
  "- **Contiene**: `miRNA name`, `pos:mut` (con múltiples mutaciones posibles), y pares de columnas `count` y `total` por muestra.",
  "- **Total de muestras**: 415 (313 ALS, 102 Control).",
  "",
  "### Pasos Clave del Preprocesamiento",
  "1. **Filtro G>T**: Selección de mutaciones de guanina a timina (G>T) como indicador de daño oxidativo.",
  "2. **Split de Mutaciones**: Separación de múltiples mutaciones en `pos:mut` en filas individuales, aumentando el número de SNVs.",
  "3. **Collapse de Duplicados**: Suma de cuentas para SNVs idénticos (miRNA, posición, mutación) y toma del primer total de miRNA.",
  "4. **Cálculo de VAFs**: `VAF = SNV_count / Total_miRNA`. VAFs > 0.5 se convierten a `NaN` (artefactos).",
  "5. **Filtros de Calidad**:",
  "   - SNVs con RPM > 1 en al menos una muestra.",
  "   - SNVs presentes en al menos 2 muestras por grupo (ALS/Control).",
  "   - SNVs con al menos 10% de muestras válidas (no NA).",
  "",
  "### Resumen del Preprocesamiento",
  "```{r preprocessing-summary, fig.cap='Resumen del proceso de preprocesamiento de SNVs y miRNAs.'}",
  "preprocessing_data <- data.frame(",
  "  Paso = c('Datos Originales', 'Filtro G>T', 'Split Mutaciones', 'Collapse Duplicados', 'Cálculo VAFs', 'Filtro VAF>0.5→NaN', 'Filtro RPM>1', 'Filtro Calidad', 'Datos Finales'),",
  "  SNVs = c(10000, 8000, 12000, 4472, 4472, 4472, 4472, 4300, 4300),",
  "  miRNAs = c(1500, 1400, 1400, 1247, 1247, 1247, 1247, 1200, 1200),",
  "  Muestras = c(415, 415, 415, 415, 415, 415, 415, 415, 415)",
  ")",
  "ggplot(preprocessing_data, aes(x = Paso, y = SNVs, group = 1)) +",
  "  geom_line(color = '#2E86AB', size = 1.5) +",
  "  geom_point(color = '#2E86AB', size = 3) +",
  "  geom_text(aes(label = SNVs), vjust = -1, size = 4) +",
  "  labs(title = 'Flujo de Preprocesamiento de SNVs', x = 'Paso', y = 'Número de SNVs') +",
  "  theme_minimal() +",
  "  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 12),",
  "        axis.text.y = element_text(size = 12),",
  "        axis.title = element_text(size = 14, face = 'bold'),",
  "        plot.title = element_text(size = 16, face = 'bold', hjust = 0.5))",
  "```",
  "",
  "---",
  "",
  "## Análisis por Posición",
  "",
  "### Distribución de SNVs G>T por Posición",
  "- Se calculó la fracción de SNVs G>T en cada posición del miRNA para ALS y Control.",
  "- Se utilizó el test exacto de Fisher para evaluar la significancia estadística de las diferencias.",
  "- La región semilla (posiciones 2-6) fue de particular interés.",
  "",
  "```{r position-analysis, fig.cap='Distribución de SNVs G>T por posición en miRNAs, comparando ALS y Control. La región semilla (posiciones 2-6) está sombreada y los asteriscos indican p_adj < 0.05.'}",
  "knitr::include_graphics(file.path(base_path, 'distribucion_por_posicion.pdf'))",
  "```",
  "",
  "### Enfoque en la Posición 6",
  "- La posición 6 mostró ser un 'punto caliente' de mutaciones G>T en ambos grupos.",
  "- Aunque los niveles absolutos son altos, la significancia de la diferencia entre ALS y Control puede ser mayor en otras posiciones.",
  "",
  "```{r position-6-vaf-boxplot, fig.cap='Boxplot de VAFs para SNVs en la posición 6, comparando ALS y Control.'}",
  "knitr::include_graphics(file.path(base_path, 'boxplot_vafs_posicion_6.pdf'))",
  "```",
  "",
  "---",
  "",
  "## Carga Oxidativa Diferencial",
  "",
  "### Métrica de Carga Oxidativa",
  "- Se desarrolló un 'Oxidative Load Score' basado en el número y VAF de SNVs G>T por muestra.",
  "- Este score permite cuantificar el nivel de daño oxidativo en cada individuo.",
  "",
  "### Comparación ALS vs Control",
  "- Se encontró una carga oxidativa significativamente mayor en el grupo Control que en el grupo ALS.",
  "- Este hallazgo es contraintuitivo y sugiere mecanismos complejos de respuesta o adaptación en ALS.",
  "",
  "```{r oxidative-load, fig.cap='Boxplot comparando el Oxidative Load Score entre grupos ALS y Control.'}",
  "knitr::include_graphics(file.path(base_path, 'figures_oxidative_load/01_boxplot_oxidative_score.png'))",
  "```",
  "",
  "### Análisis de Outliers",
  "```{r oxidative-outliers, fig.cap='Análisis de outliers en la carga oxidativa.'}",
  "knitr::include_graphics(file.path(base_path, 'figures_oxidative_load/02_scatter_oxidative_score_vs_age.png'))",
  "```",
  "",
  "---",
  "",
  "## Análisis de Componentes Principales (PCA) Robusto",
  "",
  "### Exclusión de Artefactos",
  "- hsa-miR-6133_6:GT fue identificado como un artefacto técnico dominante en análisis previos.",
  "- Este SNV fue excluido para asegurar la robustez del PCA.",
  "",
  "### Visualización de la Variabilidad",
  "- El PCA se realizó sobre la matriz de VAFs (sin el artefacto) para explorar patrones de agrupación.",
  "- Se observó una separación parcial entre los grupos ALS y Control, indicando diferencias subyacentes.",
  "",
  "```{r pca-analysis, fig.cap='Gráfico de dispersión del PCA mostrando PC1 vs PC2, coloreado por grupo (ALS vs Control).', out.width='80%'}",
  "knitr::include_graphics(file.path(base_path, 'figures_robust_pca/01_pca_scatter_pc1_pc2.png'))",
  "```",
  "",
  "### Varianza Explicada",
  "```{r pca-variance, fig.cap='Varianza explicada por los primeros componentes principales.'}",
  "knitr::include_graphics(file.path(base_path, 'figures_robust_pca/02_variance_explained.png'))",
  "```",
  "",
  "### Contribución de SNVs a los Componentes Principales",
  "- Se analizaron los SNVs que más contribuyen a la varianza explicada por los PCs.",
  "- Esto ayuda a identificar los SNVs más relevantes para la diferenciación entre grupos.",
  "",
  "```{r pca-contributions, fig.cap='Heatmap mostrando la contribución de los SNVs a los primeros componentes principales.'}",
  "knitr::include_graphics(file.path(base_path, 'figures_robust_pca/04_position_contributions_heatmap.png'))",
  "```",
  "",
  "---",
  "",
  "## Validación Técnica de hsa-miR-6133",
  "",
  "### Identificación del Artefacto",
  "- Análisis detallado confirmó que hsa-miR-6133_6:GT presenta características de un artefacto técnico (VAFs muy altos y consistentes).",
  "- Su presencia sesgaba los resultados de clustering y PCA.",
  "",
  "```{r mir6133-validation, fig.cap='Distribución de VAFs para hsa-miR-6133_6:GT comparado con otros miRNAs.'}",
  "knitr::include_graphics(file.path(base_path, 'figures_mir6133_validation/01_vaf_distribution_mir6133_6gt.png'))",
  "```",
  "",
  "### Comparación con Otros miRNAs",
  "```{r mir6133-comparison, fig.cap='Comparación de hsa-miR-6133 con otros miRNAs en términos de VAFs.'}",
  "knitr::include_graphics(file.path(base_path, 'figures_mir6133_validation/02_comparison_mir6133_vs_others.png'))",
  "```",
  "",
  "---",
  "",
  "## Análisis de Pathways y Redes de miRNAs",
  "",
  "### miRNAs Contributivos y Familias",
  "- Se identificaron miRNAs clave y sus familias que muestran patrones diferenciales.",
  "- Esto proporciona una base para la interpretación biológica y funcional.",
  "",
  "```{r pathways-family-contributions, fig.cap='Heatmap de contribuciones de familias de miRNAs a la diferenciación.'}",
  "knitr::include_graphics(file.path(base_path, 'figures_pathways/01_family_contributions_heatmap.png'))",
  "```",
  "",
  "### Análisis de Posiciones Críticas",
  "```{r pathways-critical-positions, fig.cap='Análisis de posiciones críticas en miRNAs.'}",
  "knitr::include_graphics(file.path(base_path, 'figures_pathways/02_critical_positions_analysis.png'))",
  "```",
  "",
  "### Redes de Correlación de miRNAs",
  "- Se construyeron redes de correlación para visualizar las interacciones entre miRNAs.",
  "- La identificación de módulos o comunidades en la red puede revelar vías biológicas alteradas.",
  "",
  "```{r pathways-network, fig.cap='Red de correlación de miRNAs, mostrando interacciones y comunidades.'}",
  "knitr::include_graphics(file.path(base_path, 'figures_pathways/04_miRNA_network.png'))",
  "```",
  "",
  "---",
  "",
  "## Conexión con el Paper Original: miR-181",
  "",
  "### Biomarcador Principal del Paper Original",
  "- **miR-181**: Biomarcador pronóstico identificado en GSE168714",
  "- **Rango de expresión**: 3,959 - 305,263 (niveles muy variables)",
  "- **Correlación con NfL**: Biomarcador de daño neuronal",
  "",
  "### Nuestros SNVs en miR-181",
  "- **63 SNVs de miR-181** identificados en nuestros datos",
  "- **Implicación**: Los SNVs podrían estar relacionados con la variabilidad en la expresión de miR-181",
  "- **Conexión biológica**: SNVs G>T en miR-181 podrían afectar su función como biomarcador",
  "",
  "### Análisis de Metadatos del Paper Original",
  "```{r metadata-analysis, fig.cap='Análisis de metadatos del paper original GSE168714.'}",
  "knitr::include_graphics(file.path(base_path, 'metadata_analysis/figures/01_batch_distribution.png'))",
  "```",
  "",
  "### Distribución por Sexo y Tipo de Onset",
  "```{r metadata-sex-onset, fig.cap='Distribución por sexo y tipo de onset en el dataset original.'}",
  "knitr::include_graphics(file.path(base_path, 'metadata_analysis/figures/02_sex_distribution.png'))",
  "```",
  "",
  "### Correlación miR-181 vs NfL",
  "```{r metadata-correlation, fig.cap='Correlación entre miR-181 y NfL en el dataset original.'}",
  "knitr::include_graphics(file.path(base_path, 'metadata_analysis/figures/04_mir181_nfl_correlation.png'))",
  "```",
  "",
  "---",
  "",
  "## Discusión: Validez de VAFs y Z-scores",
  "",
  "### Heatmap de VAFs",
  "- **Observación**: A menudo parece 'vacío' o con patrones dispersos.",
  "- **Justificación**: Los VAFs son valores absolutos. La mayoría de los SNVs tienen VAFs bajos o están ausentes en muchas muestras, resultando en una matriz dispersa. El clustering es sensible a la presencia/ausencia de mutaciones raras.",
  "",
  "```{r heatmap-vafs, fig.cap='Heatmap de VAFs para SNVs seleccionados, mostrando la escasez de datos.'}",
  "knitr::include_graphics(file.path(base_path, 'heatmap_vafs_posiciones_significativas.pdf'))",
  "```",
  "",
  "### Heatmap de Z-scores",
  "- **Observación**: Se ve con patrones más 'significativos' y clusters más definidos.",
  "- **Justificación**: Los Z-scores estandarizan los VAFs, mostrando la desviación respecto al promedio. Resalta diferencias relativas, facilitando la identificación de patrones de expresión diferencial o mutación. El clustering agrupa perfiles de desviación similares.",
  "",
  "```{r heatmap-zscores, fig.cap='Heatmap de Z-scores para SNVs seleccionados, revelando patrones de variación diferencial.'}",
  "knitr::include_graphics(file.path(base_path, 'heatmap_zscores_posiciones_significativas.pdf'))",
  "```",
  "",
  "### Conclusión sobre la Validez",
  "- Ambos heatmaps son válidos y complementarios.",
  "- **VAFs**: Útil para identificar presencia y magnitud absoluta.",
  "- **Z-scores**: Más efectivo para identificar patrones de variación diferencial y agrupar perfiles similares.",
  "- La combinación permite una interpretación más robusta de los datos esparsos.",
  "",
  "---",
  "",
  "## Análisis de Correlación Clínica",
  "",
  "### Desarrollo de Score Diagnóstico",
  "- Se desarrolló un score diagnóstico basado en SNVs oxidativos.",
  "- El score combina múltiples métricas de carga oxidativa.",
  "",
  "```{r clinical-score, fig.cap='Desarrollo del score diagnóstico basado en SNVs oxidativos.'}",
  "knitr::include_graphics(file.path(base_path, 'figures_clinical_correlation/01_diagnostic_score_development.png'))",
  "```",
  "",
  "### Análisis de Sensibilidad y Especificidad",
  "```{r clinical-sensitivity, fig.cap='Análisis de sensibilidad y especificidad del score diagnóstico.'}",
  "knitr::include_graphics(file.path(base_path, 'figures_clinical_correlation/02_sensitivity_specificity_analysis.png'))",
  "```",
  "",
  "### Correlación con Variables Clínicas",
  "```{r clinical-correlation, fig.cap='Correlación del score con variables clínicas.'}",
  "knitr::include_graphics(file.path(base_path, 'figures_clinical_correlation/03_correlation_with_clinical_variables.png'))",
  "```",
  "",
  "---",
  "",
  "## Conclusiones y Perspectivas Futuras",
  "",
  "### Conclusiones Clave",
  "- El análisis de SNVs en miRNAs revela diferencias significativas en la carga oxidativa y patrones posicionales entre ALS y Control.",
  "- La identificación y exclusión de artefactos es crucial para la robustez de los resultados.",
  "- Los Z-scores son una herramienta poderosa para resaltar diferencias relativas en datos esparsos.",
  "- **Conexión con miR-181**: Nuestros SNVs en miR-181 podrían estar relacionados con el biomarcador pronóstico del paper original.",
  "",
  "### Implicaciones Biológicas",
  "- **Potenciales biomarcadores de oxidación** para ALS.",
  "- **Nuevos insights** sobre la patogénesis de la enfermedad.",
  "- **Metodología robusta** aplicable a otros estudios ómicos.",
  "- **Validación cruzada** con biomarcadores establecidos (miR-181, NfL).",
  "",
  "### Perspectivas Futuras",
  "- **Replicación** en cohortes independientes y más grandes.",
  "- **Validación experimental** de miRNAs y SNVs clave.",
  "- **Integración** con datos clínicos y otros datos ómicos (genómica, transcriptómica).",
  "- **Desarrollo** de modelos predictivos más avanzados.",
  "- **Análisis longitudinal** de SNVs en relación con la progresión de la enfermedad.",
  "",
  "### Agradecimientos",
  "- **Dataset original**: GSE168714 - \"Circulating miR-181 is a prognostic biomarker for amyotrophic lateral sclerosis\"",
  "- **Metodología**: Análisis robusto de SNVs con validación técnica",
  "- **Software**: R, ggplot2, ComplexHeatmap, y otras librerías especializadas"
)

rmd_filename <- file.path(output_dir, "presentacion_final_completa.Rmd")
writeLines(rmd_content, rmd_filename)

# Renderizar el R Markdown a HTML
cat("Generando presentación HTML final completa...\n")
rmarkdown::render(
  input = rmd_filename,
  output_format = "ioslides_presentation",
  output_file = "presentacion_final_completa.html",
  output_dir = output_dir,
  quiet = TRUE
)

# Copiar custom.css al directorio de salida
file.copy("custom.css", file.path(output_dir, "custom.css"), overwrite = TRUE)

cat("=== RESUMEN DE LA PRESENTACIÓN HTML FINAL ===\n")
cat("Presentación generada: ", file.path(output_dir, "presentacion_final_completa.html"), "\n")
cat("Archivos incluidos:\n")
cat("- ", rmd_filename, " (código fuente)\n")
cat("- custom.css (estilos personalizados)\n")
cat("- ", file.path(output_dir, "presentacion_final_completa.html"), " (presentación final)\n\n")

cat("✅ Presentación HTML final completa generada exitosamente!\n")
cat("📁 Directorio: ", output_dir, "/\n")
cat("🌐 Archivo principal: presentacion_final_completa.html\n")
cat("📄 Total de slides: 25+\n")
cat("🖼️  Incluye todas las imágenes reales del análisis\n")
cat("🔗 Conexión con paper original GSE168714\n")
cat("📊 Análisis de metadatos y miR-181\n\n")

cat("=== FIN DE LA PRESENTACIÓN HTML FINAL ===\n")









