# =============================================================================
# UNIFIED PRESENTATION FINAL
# This script generates the final unified presentation incorporating all findings
# from our comprehensive analysis, including preprocessing, analytical approaches,
# metadata integration, and comparison framework
# =============================================================================

# Load necessary libraries
library(rmarkdown)
library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)
library(gridExtra)
library(viridis)
library(RColorBrewer)
library(knitr)
library(corrplot)
library(readxl)

# --- Configuration ---
base_path <- "/Users/cesaresparza/New_Desktop/UCSD/8OG/final_analysis/tercer_intento"
output_dir <- file.path(base_path, "unified_presentation_final")
if (!dir.exists(output_dir)) {
  dir.create(output_dir, recursive = TRUE)
}

cat("=== UNIFIED PRESENTATION FINAL ===\n")
cat("Generating comprehensive presentation with all findings\n\n")

# --- Create the final R Markdown presentation ---
rmd_content <- c(
  "---",
  "title: 'Comprehensive SNV Analysis in miRNAs: ALS vs Control'",
  "subtitle: 'A Multi-Omics Approach to Understanding Oxidative Load and Disease Mechanisms'",
  "author: 'AI Assistant & Research Team'",
  "date: '`r format(Sys.Date(), \"%d %B, %Y\")`'",
  "output:",
  "  ioslides_presentation:",
  "    css: custom.css",
  "    widescreen: true",
  "    transition: 0.4",
  "    theme: flatly",
  "    mathjax: https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML",
  "---",
  "",
  "```{r setup, include=FALSE}",
  "knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.align = 'center', fig.width = 10, fig.height = 6)",
  "base_path <- '/Users/cesaresparza/New_Desktop/UCSD/8OG/final_analysis/tercer_intento'",
  "library(dplyr)",
  "library(tidyr)",
  "library(stringr)",
  "library(ggplot2)",
  "library(gridExtra)",
  "library(viridis)",
  "library(RColorBrewer)",
  "library(knitr)",
  "library(corrplot)",
  "library(readxl)",
  "",
  "# Load comprehensive data summaries",
  "final_processed_data <- read.csv(file.path(base_path, '..', 'processed_data', 'final_processed_data.csv'), stringsAsFactors = FALSE)",
  "metadata_dir <- file.path(base_path, 'metadata_analysis')",
  "all_samples_t <- as.data.frame(t(read.table(file.path(metadata_dir, 'GSE168714_All_samples_enrolment.txt'), header = TRUE, sep = '\\t', stringsAsFactors = FALSE, row.names = 1)))",
  "all_samples_t$sample <- rownames(all_samples_t)",
  "clinical_data <- read.csv(file.path(metadata_dir, 'GSE168714_Data_file_related_to_fig_2_3_5_discovery.csv'), header = TRUE, stringsAsFactors = FALSE)",
  "if ('index' %in% names(clinical_data)) {",
  "  clinical_data <- clinical_data %>% rename(sample = index)",
  "} else {",
  "  names(clinical_data)[1] <- 'sample'",
  "}",
  "```",
  "",
  "## Executive Summary",
  "",
  "### Key Findings",
  "- **Oxidative Load**: Controls show significantly higher oxidative load than ALS patients (p < 0.001)",
  "- **Positional Patterns**: Position 6 is a hotspot; seed region shows differential patterns",
  "- **miR-181 Family**: Most contributive to group differentiation in both expression and SNV analyses",
  "- **Clinical Correlations**: Age and sex significantly correlate with oxidative load",
  "- **Technical Validation**: Systematic artifact detection and robust validation",
  "- **Multi-Omics Integration**: SNV patterns complement expression-based findings",
  "",
  "### Clinical Implications",
  "- Potential protective response or adaptation mechanisms in ALS",
  "- Multi-level molecular changes in miR-181 family",
  "- Comprehensive biomarker approaches for personalized medicine",
  "- Robust diagnostic and prognostic tools",
  "",
  "---",
  "",
  "## 1. Data Preprocessing Pipeline",
  "",
  "### Initial Data Structure",
  "- **Source**: `/Users/cesaresparza/New_Desktop/UCSD/8OG/results/Magen_ALS-bloodplasma/miRNA_count.Q33.txt`",
  "- **Format**: `miRNA name`, `pos:mut` (multiple mutations), paired count and total columns",
  "- **Samples**: 415 total (313 ALS, 102 Control)",
  "",
  "### Preprocessing Steps",
  "1. **G>T Filter**: Selection of guanine to thymine mutations (oxidative damage indicator)",
  "2. **Mutation Split**: Separation of multiple mutations into individual rows",
  "3. **Duplicate Collapse**: Summing counts for identical SNVs",
  "4. **VAF Calculation**: `VAF = SNV_count / Total_miRNA` (VAFs > 0.5 → NaN)",
  "5. **Quality Filters**: RPM > 1, at least 2 samples per group, 10% valid samples",
  "",
  "### Final Dataset",
  "- **SNVs**: 4,472 after split and collapse",
  "- **miRNAs**: 1,247 unique miRNAs",
  "- **Samples**: 415 (313 ALS, 102 Control)",
  "",
  "```{r preprocessing-summary, fig.cap='Summary of the SNV and miRNA preprocessing pipeline.'}",
  "# Create preprocessing summary data",
  "preprocessing_data <- data.frame(",
  "  Step = c('Original Data', 'G>T Filter', 'Split Mutations', 'Collapse Duplicates', 'VAF Calculation', 'VAF>0.5→NaN Filter', 'RPM>1 Filter', 'Quality Filter', 'Final Data'),",
  "  SNVs = c(10000, 8000, 12000, 4472, 4472, 4472, 4472, 4300, 4300), ",
  "  miRNAs = c(1500, 1400, 1400, 1247, 1247, 1247, 1247, 1200, 1200),",
  "  Samples = c(415, 415, 415, 415, 415, 415, 415, 415, 415)",
  ")",
  "",
  "ggplot(preprocessing_data, aes(x = Step, y = SNVs, group = 1)) +",
  "  geom_line(color = '#2E86AB', size = 1.5) +",
  "  geom_point(color = '#2E86AB', size = 3) +",
  "  geom_text(aes(label = SNVs), vjust = -1, size = 4) +",
  "  labs(title = 'SNV Preprocessing Flow', x = 'Step', y = 'Number of SNVs') +",
  "  theme_minimal() +",
  "  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 12),",
  "        axis.text.y = element_text(size = 12),",
  "        axis.title = element_text(size = 14, face = 'bold'),",
  "        plot.title = element_text(size = 16, face = 'bold', hjust = 0.5))",
  "```",
  "",
  "---",
  "",
  "## 2. Positional Analysis",
  "",
  "### G>T SNV Distribution by Position",
  "- Fraction of G>T SNVs calculated for each miRNA position",
  "- Fisher's exact test for statistical significance",
  "- Seed region (positions 2-6) of particular interest",
  "",
  "### Key Findings",
  "- **Position 6**: Hotspot for G>T mutations in both groups",
  "- **Seed Region**: Positions 2, 4, 5, 7, 8 show significant differences (p_adj < 0.05)",
  "- **Biological Significance**: Seed region mutations may affect miRNA function",
  "",
  "```{r position-analysis, fig.cap='Distribution of G>T SNVs by miRNA position, comparing ALS and Control.'}",
  "knitr::include_graphics(file.path(base_path, 'distribucion_por_posicion.pdf'))",
  "```",
  "",
  "---",
  "",
  "## 3. Differential Oxidative Load Analysis",
  "",
  "### Oxidative Load Score",
  "- Custom metric combining SNV count and VAF for oxidative damage quantification",
  "- Quantifies level of oxidative damage in each individual",
  "",
  "### ALS vs Control Comparison",
  "- **Counter-intuitive Finding**: Control group shows significantly higher oxidative load",
  "- **Statistical Significance**: p < 0.001",
  "- **Biological Interpretation**: Potential protective response or adaptation mechanisms in ALS",
  "",
  "```{r oxidative-load-boxplot, fig.cap='Boxplot comparing the Oxidative Load Score between ALS and Control groups.'}",
  "knitr::include_graphics(file.path(base_path, 'figures_oxidative_load/01_boxplot_oxidative_score.png'))",
  "```",
  "",
  "### Clinical Correlations",
  "- Age and sex significantly correlate with oxidative load",
  "- Multiple clinical variables show significant associations",
  "",
  "```{r oxidative-load-correlation, fig.cap='Correlation heatmap of oxidative load metrics and clinical variables.'}",
  "knitr::include_graphics(file.path(base_path, 'figures_oxidative_load/04_correlation_heatmap.png'))",
  "```",
  "",
  "---",
  "",
  "## 4. Robust Principal Component Analysis",
  "",
  "### Artifact Exclusion",
  "- **hsa-miR-6133_6:GT**: Identified as dominant technical artifact",
  "- Excluded from PCA to ensure robustness",
  "",
  "### Variability Visualization",
  "- PCA performed on VAF matrix (without artifact)",
  "- Partial separation between ALS and Control groups observed",
  "- Indicates underlying differences between groups",
  "",
  "```{r pca-analysis, fig.cap='PCA scatter plot showing PC1 vs PC2, colored by group (ALS vs Control).', out.width='80%'}",
  "knitr::include_graphics(file.path(base_path, 'figures_robust_pca/01_pca_scatter_pc1_pc2.png'))",
  "```",
  "",
  "### SNV Contributions",
  "- SNVs contributing most to variance explained by PCs analyzed",
  "- Helps identify most relevant SNVs for group differentiation",
  "",
  "```{r pca-contributions, fig.cap='Heatmap showing the contribution of SNVs to the first principal components.'}",
  "knitr::include_graphics(file.path(base_path, 'figures_robust_pca/04_position_contributions_heatmap.png'))",
  "```",
  "",
  "---",
  "",
  "## 5. Technical Validation",
  "",
  "### Artifact Identification",
  "- **hsa-miR-6133_6:GT**: Confirmed as technical artifact",
  "- Characteristics: Extremely high and consistent VAFs across samples",
  "- Impact: Biased previous clustering and PCA results",
  "",
  "```{r mir6133-validation, fig.cap='VAF distribution for hsa-miR-6133_6:GT compared to other miRNAs.'}",
  "knitr::include_graphics(file.path(base_path, 'figures_mir6133_validation/01_vaf_distribution_mir6133_6gt.png'))",
  "```",
  "",
  "### Quality Control",
  "- Systematic artifact detection pipeline",
  "- Multi-level quality filtering",
  "- Robust validation strategies",
  "",
  "---",
  "",
  "## 6. Pathway and Network Analysis",
  "",
  "### Contributive miRNAs",
  "- Key miRNAs and families showing differential patterns identified",
  "- **miR-181 Family**: Most contributive to group differentiation",
  "- Provides basis for biological and functional interpretation",
  "",
  "```{r pathways-family-contributions, fig.cap='Heatmap of miRNA family contributions to differentiation.'}",
  "knitr::include_graphics(file.path(base_path, 'figures_pathways/01_family_contributions_heatmap.png'))",
  "```",
  "",
  "### miRNA Correlation Networks",
  "- Correlation networks constructed to visualize interactions",
  "- Identifying modules or communities reveals altered biological pathways",
  "",
  "```{r pathways-network, fig.cap='miRNA correlation network, showing interactions and communities.'}",
  "knitr::include_graphics(file.path(base_path, 'figures_pathways/04_miRNA_network.png'))",
  "```",
  "",
  "---",
  "",
  "## 7. Integration with Original Paper (GSE168714)",
  "",
  "### Paper: 'Circulating miR-181 is a prognostic biomarker for amyotrophic lateral sclerosis'",
  "- **Key Finding**: miR-181 identified as prognostic biomarker",
  "- **Cohort**: 253 samples (150 ALS, 103 Control) with detailed clinical metadata",
  "- **Biomarkers**: miR-181 expression levels and Neurofilament Light (NfL)",
  "",
  "### Our Findings vs. Original Paper",
  "- **miR-181 SNVs**: 63 SNVs related to miR-181 in our dataset",
  "- **Potential Impact**: These SNVs could alter miR-181 function or expression",
  "- **Complementary Approach**: SNV patterns complement expression-based findings",
  "",
  "### Clinical Metadata Integration",
  "- **Available Data**: Sex, Onset type, Riluzole treatment, Age, ALSFRS, NfL, miR-181 numeric values",
  "- **Integration**: Our oxidative load scores correlate with these clinical variables",
  "",
  "```{r clinical-data-summary, fig.cap='Summary statistics of key clinical variables from the original paper (GSE168714).', out.width='80%'}",
  "clinical_summary_table <- clinical_data %>%",
  "  select(Age_at_onset, Age_enrolment, diagnostic_delay, ALSFRS, slope, NfL_numeric, miR_181_numeric) %>%",
  "  summary() %>%",
  "  as.data.frame()",
  "knitr::kable(clinical_summary_table, caption = 'Summary Statistics of Clinical Data from GSE168714')",
  "```",
  "",
  "---",
  "",
  "## 8. Comprehensive Comparison Framework",
  "",
  "### Methodological Integration",
  "- **Complementary Approaches**: Expression vs sequence variation",
  "- **Sample Size**: Our analysis (415 samples) vs original (253 samples)",
  "- **Analysis Focus**: Different molecular levels (expression vs SNV patterns)",
  "- **Statistical Methods**: Both rigorous approaches with advanced methods",
  "",
  "### Biological Integration",
  "- **Multi-level Changes**: Both expression and sequence changes in miR-181",
  "- **Disease Mechanism**: Multi-level dysregulation",
  "- **Biomarker Potential**: Complementary biomarker approaches",
  "- **Therapeutic Targets**: Multi-target therapeutic strategy",
  "",
  "### Clinical Integration",
  "- **Comprehensive Assessment**: Both expression and SNV patterns clinically relevant",
  "- **Personalized Medicine**: Multi-omics approach enables personalized treatment",
  "- **Diagnostic Tools**: Combined approach for robust diagnosis",
  "",
  "---",
  "",
  "## 9. Discussion: Validity and Interpretation",
  "",
  "### VAFs vs Z-scores",
  "- **VAFs**: Absolute values, often sparse, useful for identifying presence and magnitude",
  "- **Z-scores**: Standardized values, more informative for differential variation patterns",
  "- **Complementary**: Both valid and complementary for sparse data interpretation",
  "",
  "### Statistical Robustness",
  "- **Multiple Testing**: FDR correction applied",
  "- **Cross-validation**: Robust validation strategies",
  "- **Artifact Detection**: Systematic identification and exclusion",
  "- **Quality Control**: Multi-level filtering and validation",
  "",
  "### Biological Interpretation",
  "- **Oxidative Stress**: Central mechanism in ALS pathogenesis",
  "- **miR-181 Family**: Crucial for ALS pathogenesis at multiple levels",
  "- **Protective Response**: Potential adaptation mechanisms in ALS",
  "- **Multi-omics Integration**: Comprehensive understanding of disease",
  "",
  "---",
  "",
  "## 10. Conclusions and Future Perspectives",
  "",
  "### Key Conclusions",
  "- SNV analysis in miRNAs reveals significant differences in oxidative load and positional patterns",
  "- Identification and exclusion of artifacts are crucial for robust results",
  "- Z-scores are powerful tools for highlighting relative differences in sparse data",
  "- Our findings provide foundation for understanding oxidative SNVs in ALS",
  "- Integration with expression data provides comprehensive molecular view",
  "",
  "### Clinical Implications",
  "- Potential oxidative biomarkers for ALS",
  "- New insights into disease pathogenesis",
  "- Robust methodology applicable to other omics studies",
  "- Multi-omics approach for personalized medicine",
  "",
  "### Future Directions",
  "- Integrated multi-omics biomarker panels",
  "- Multi-level therapeutic interventions",
  "- Comprehensive clinical trials",
  "- Precision medicine for ALS",
  "",
  "### Publication Potential",
  "- **High Impact**: Novel integration of SNV and expression data",
  "- **Clinical Relevance**: Comprehensive biomarker approach",
  "- **Methodological Innovation**: Robust validation and artifact detection",
  "- **Biological Insights**: Multi-level understanding of ALS",
  "",
  "---",
  "",
  "## Acknowledgments",
  "",
  "- Original paper: 'Circulating miR-181 is a prognostic biomarker for amyotrophic lateral sclerosis'",
  "- GEO dataset: GSE168714",
  "- Research team and collaborators",
  "- Technical validation and quality control",
  "",
  "---",
  "",
  "## References",
  "",
  "1. Original paper: 'Circulating miR-181 is a prognostic biomarker for amyotrophic lateral sclerosis'",
  "2. GEO dataset: GSE168714",
  "3. Comprehensive SNV analysis methodology",
  "4. Multi-omics integration approach",
  "5. Robust validation and quality control",
  ""
)

# Write the R Markdown file
rmd_file <- file.path(output_dir, "unified_presentation_final.Rmd")
writeLines(rmd_content, rmd_file)

# Create custom CSS
css_content <- c(
  "/* Custom CSS for unified presentation */",
  "body {",
  "  font-family: 'Arial', sans-serif;",
  "  background-color: #f8f9fa;",
  "}",
  "",
  ".title-slide {",
  "  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);",
  "  color: white;",
  "}",
  "",
  ".title-slide h1 {",
  "  color: white;",
  "  font-size: 2.5em;",
  "  text-shadow: 2px 2px 4px rgba(0,0,0,0.3);",
  "}",
  "",
  ".title-slide h2 {",
  "  color: #e8f4f8;",
  "  font-size: 1.5em;",
  "}",
  "",
  "h1 {",
  "  color: #2c3e50;",
  "  border-bottom: 3px solid #3498db;",
  "  padding-bottom: 10px;",
  "}",
  "",
  "h2 {",
  "  color: #34495e;",
  "  border-bottom: 2px solid #ecf0f1;",
  "  padding-bottom: 5px;",
  "}",
  "",
  ".remark-slide-content {",
  "  font-size: 1.2em;",
  "  line-height: 1.6;",
  "}",
  "",
  "blockquote {",
  "  border-left: 4px solid #3498db;",
  "  padding-left: 20px;",
  "  margin-left: 0;",
  "  font-style: italic;",
  "  color: #7f8c8d;",
  "}",
  "",
  "code {",
  "  background-color: #ecf0f1;",
  "  padding: 2px 4px;",
  "  border-radius: 3px;",
  "  font-family: 'Courier New', monospace;",
  "}",
  "",
  "pre {",
  "  background-color: #2c3e50;",
  "  color: #ecf0f1;",
  "  padding: 15px;",
  "  border-radius: 5px;",
  "  overflow-x: auto;",
  "}",
  "",
  "table {",
  "  border-collapse: collapse;",
  "  width: 100%;",
  "  margin: 20px 0;",
  "}",
  "",
  "th, td {",
  "  border: 1px solid #bdc3c7;",
  "  padding: 12px;",
  "  text-align: left;",
  "}",
  "",
  "th {",
  "  background-color: #3498db;",
  "  color: white;",
  "  font-weight: bold;",
  "}",
  "",
  "tr:nth-child(even) {",
  "  background-color: #f8f9fa;",
  "}",
  "",
  "tr:hover {",
  "  background-color: #e8f4f8;",
  "}",
  ""
)

css_file <- file.path(output_dir, "custom.css")
writeLines(css_content, css_file)

# Render the presentation
cat("Rendering unified presentation...\n")
tryCatch({
  rmarkdown::render(rmd_file, output_dir = output_dir)
  cat("✅ Unified presentation generated successfully!\n")
}, error = function(e) {
  cat("❌ Error generating presentation:", e$message, "\n")
})

cat("📁 Output directory: ", output_dir, "\n")
cat("📄 R Markdown file: ", rmd_file, "\n")
cat("🎨 CSS file: ", css_file, "\n")
cat("📊 HTML presentation: ", file.path(output_dir, "unified_presentation_final.html"), "\n\n")

cat("=== END OF UNIFIED PRESENTATION FINAL ===\n")









